apiVersion: v1
kind: Service
metadata:
  name: wallet-service
spec:
  selector:
    app: wallet-api
  ports:
    - protocol: 'TCP'
      # port accessible inside cluster
      port: 8080
      # port to forward inside pod
      targetPort: 80
      # port accessible outside cluster
      nodePort: 30001
  type: LoadBalancer
